name: Test Workflow

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
        description: 'Back or frontend deployment type'
      postman_collection:
        required: false
        type: string
        description: 'Collection id for postman tests'
    secrets:
      POSTMAN_API_KEY:
        required: false
      CARGO_REGISTRY_TOKEN:
        required: false

jobs:

  run-back:
    if: ${{ inputs.type == 'back' }}
    uses: ./.github/workflows/back_ci.yml
    with:
      postman_collection: ${{ inputs.postman_collection }}
    secrets:
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}

  run-front:
    if: ${{ inputs.type == 'front' }}
    uses: ./.github/workflows/front_ci.yml

  run-api-lib-ci:
    if: ${{ inputs.type == 'ci-back-lib' }}
    uses: ./.github/workflows/ci-back-lib.yml

  run-api-lib-cd:
    if: ${{ inputs.type == 'cd-back-lib' }}
    uses: ./.github/workflows/cd-back-lib.yml
    secrets:
      MAIRIE_360_DEPLOY_TOKEN: ${{ secrets.MAIRIE_360_DEPLOY_TOKEN }}
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
